eureka:
  name: GRANT
  client:
    serviceUrl:
      defaultZone: https://user:gnm123Bc@grant-discovery-service.herokuapp.com/eureka/
---
spring:
  profiles: heroku
eureka:
  instance:
    hostname: https://grant-sys.herokuapp.com/
    nonSecurePort: 80
  password: ${USER_PASSWORD:password}